const mongoose = require('mongoose');
const Tag = require('../../banking/models/Tag');

const installmentSchema = new mongoose.Schema({
  description: {
    type: String,
    required: true,
    trim: true,
    maxlength: 200
  },
  installmentType: {
    type: String,
    enum: ['investment', 'tax', 'lawyer', 'other'],
    required: true,
    default: 'investment'
  },
  amount: {
    type: Number,
    required: true,
    min: 0
  },
  percentage: {
    type: Number,
    default: null,
    min: 0,
    max: 100
  },
  includeTax: {
    type: Boolean,
    default: false
  },
  taxPercentage: {
    type: Number,
    default: null,
    min: 0,
    max: 100
  },
  currency: {
    type: String,
    default: 'USD'
  },
  dueDate: {
    type: Date,
    required: true
  },
  status: {
    type: String,
    enum: ['pending', 'paid', 'overdue'],
    default: 'pending'
  },
  paidDate: {
    type: Date,
    default: null
  },
  linkedTransactions: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Transaction'
  }],
  fundingSourceId: {
    type: mongoose.Schema.Types.ObjectId,
    default: null
  },
  autoGenerated: {
    type: String,
    default: null,
    enum: [null, 'mortgage', 'final-payment']
  },
  notes: {
    type: String,
    trim: true,
    maxlength: 500
  }
});

const rentalIncomeSchema = new mongoose.Schema({
  month: {
    type: Date,
    required: true
  },
  expectedAmount: {
    type: Number,
    required: true,
    min: 0
  },
  actualAmount: {
    type: Number,
    default: null
  },
  received: {
    type: Boolean,
    default: false
  },
  notes: {
    type: String,
    trim: true,
    maxlength: 200
  }
});

const realEstateInvestmentSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  name: {
    type: String,
    required: true,
    trim: true,
    maxlength: 100
  },
  type: {
    type: String,
    enum: ['flip', 'rental'],
    required: true
  },
  status: {
    type: String,
    enum: ['active', 'completed', 'sold', 'cancelled'],
    default: 'active'
  },

  // Property details
  address: {
    type: String,
    trim: true,
    maxlength: 300
  },
  description: {
    type: String,
    trim: true,
    maxlength: 1000
  },

  // Financial
  totalInvestment: {
    type: Number,
    default: 0,
    min: 0
  },
  estimatedCurrentValue: {
    type: Number,
    default: 0,
    min: 0
  },
  currency: {
    type: String,
    required: true,
    default: 'USD'
  },
  purchaseTaxRate: {
    type: Number,
    default: null,
    min: 0,
    max: 100
  },
  country: {
    type: String,
    trim: true,
    maxlength: 100,
    default: null
  },
  taxPresetId: {
    type: String,
    trim: true,
    maxlength: 50,
    default: null
  },

  // Funding sources (same pattern as Projects)
  fundingSources: [{
    type: {
      type: String,
      enum: ['loan', 'savings', 'partner', 'mortgage', 'other'],
      required: true
    },
    description: {
      type: String,
      required: true,
      trim: true,
      maxlength: 200
    },
    expectedAmount: {
      type: Number,
      required: true,
      min: 0
    },
    availableAmount: {
      type: Number,
      default: 0,
      min: 0
    },
    currency: {
      type: String,
      default: 'USD'
    }
  }],

  // Budget breakdown by category
  categoryBudgets: [{
    categoryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category'
    },
    subCategoryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'SubCategory'
    },
    budgetedAmount: {
      type: Number,
      required: true,
      min: 0
    },
    allocatedTransactions: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Transaction'
    }],
    currency: {
      type: String,
      default: 'USD'
    },
    description: {
      type: String,
      trim: true,
      maxlength: 200
    }
  }],

  // Installments (planned payments: investment, taxes, lawyer fees, etc.)
  installments: [installmentSchema],

  // Flip-specific fields
  salePrice: {
    type: Number,
    default: null,
    min: 0
  },
  saleDate: {
    type: Date,
    default: null
  },
  saleExpenses: {
    type: Number,
    default: 0,
    min: 0
  },

  // Rental-specific fields
  monthlyRent: {
    type: Number,
    default: null,
    min: 0
  },
  estimatedMonthlyRental: {
    type: Number,
    default: null,
    min: 0
  },
  mortgagePercentage: {
    type: Number,
    default: null,
    min: 0,
    max: 100
  },
  mortgageInterestRate: {
    type: Number,
    default: null,
    min: 0,
    max: 100
  },
  mortgageTermYears: {
    type: Number,
    default: null,
    min: 1,
    max: 50
  },
  tenantName: {
    type: String,
    trim: true,
    maxlength: 100
  },
  leaseStart: {
    type: Date,
    default: null
  },
  leaseEnd: {
    type: Date,
    default: null
  },
  rentalIncome: [rentalIncomeSchema],

  // Linked bank account (auto-tag its transactions)
  linkedBankAccountId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'BankAccount',
    default: null
  },

  // Auto-generated tag for transaction linking
  investmentTag: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Tag',
    default: null
  },

  notes: {
    type: String,
    trim: true,
    maxlength: 2000
  }
}, {
  timestamps: true
});

// Indexes
realEstateInvestmentSchema.index({ userId: 1, name: 1 }, { unique: true });
realEstateInvestmentSchema.index({ userId: 1, status: 1 });
realEstateInvestmentSchema.index({ userId: 1, type: 1 });

// Virtuals
realEstateInvestmentSchema.virtual('totalPendingInstallments').get(function() {
  return this.installments
    .filter(i => i.status === 'pending' || i.status === 'overdue')
    .reduce((sum, i) => sum + i.amount, 0);
});

realEstateInvestmentSchema.virtual('totalPaidInstallments').get(function() {
  return this.installments
    .filter(i => i.status === 'paid')
    .reduce((sum, i) => sum + i.amount, 0);
});

realEstateInvestmentSchema.virtual('flipGain').get(function() {
  if (this.type !== 'flip' || !this.salePrice) return null;
  return this.salePrice - this.saleExpenses - this.totalInvestment;
});

realEstateInvestmentSchema.virtual('totalRentalIncome').get(function() {
  return this.rentalIncome
    .filter(r => r.received)
    .reduce((sum, r) => sum + (r.actualAmount ?? r.expectedAmount), 0);
});

realEstateInvestmentSchema.virtual('estimatedMonthlyMortgage').get(function() {
  if (this.mortgagePercentage == null || this.mortgageInterestRate == null ||
      this.mortgageTermYears == null || this.estimatedCurrentValue == null) return null;
  if (this.mortgagePercentage === 0 || this.estimatedCurrentValue === 0) return 0;
  const principal = this.estimatedCurrentValue * (this.mortgagePercentage / 100);
  const monthlyRate = (this.mortgageInterestRate / 100) / 12;
  if (monthlyRate === 0) return principal / (this.mortgageTermYears * 12);
  const n = this.mortgageTermYears * 12;
  return (principal * monthlyRate * Math.pow(1 + monthlyRate, n)) / (Math.pow(1 + monthlyRate, n) - 1);
});

realEstateInvestmentSchema.set('toJSON', { virtuals: true });
realEstateInvestmentSchema.set('toObject', { virtuals: true });

// Static methods
realEstateInvestmentSchema.statics.findByUser = async function(userId, options = {}) {
  const query = { userId };
  if (options.type) query.type = options.type;
  if (options.status) query.status = options.status;

  return this.find(query)
    .populate('investmentTag', 'name')
    .populate('linkedBankAccountId', 'name bankId')
    .sort({ createdAt: -1 });
};

realEstateInvestmentSchema.statics.findActive = async function(userId) {
  return this.find({ userId, status: 'active' })
    .populate('investmentTag', 'name')
    .populate('linkedBankAccountId', 'name bankId')
    .sort({ createdAt: -1 });
};

// Create investment tag
realEstateInvestmentSchema.methods.createInvestmentTag = async function() {
  const tagName = `realestate:${this.name.toLowerCase().replace(/\s+/g, '-')}`.substring(0, 50);

  const tag = await Tag.findOrCreate({
    name: tagName,
    userId: this.userId,
    type: 'real-estate',
    projectMetadata: {
      description: this.address,
      status: this.status
    }
  });

  this.investmentTag = tag._id;
  await this.save();

  return tag;
};

// Mark as sold (flip)
realEstateInvestmentSchema.methods.markSold = async function(salePrice, saleDate, saleExpenses = 0) {
  this.salePrice = salePrice;
  this.saleDate = saleDate || new Date();
  this.saleExpenses = saleExpenses;
  this.status = 'sold';
  await this.save();

  if (this.investmentTag) {
    await Tag.updateOne(
      { _id: this.investmentTag },
      { 'projectMetadata.status': 'sold' }
    );
  }

  return this;
};

// Update overdue installments
realEstateInvestmentSchema.methods.updateOverdueInstallments = function() {
  const now = new Date();
  let changed = false;
  for (const i of this.installments) {
    if (i.status === 'pending' && i.dueDate < now) {
      i.status = 'overdue';
      changed = true;
    }
  }
  return changed;
};

// Generate or update auto-installments based on mortgage and property value
realEstateInvestmentSchema.methods.generateAutoInstallments = function() {
  const value = this.estimatedCurrentValue || 0;
  const currency = this.currency || 'USD';
  const taxRate = this.purchaseTaxRate || 0;
  const taxAmount = value * (taxRate / 100);
  const mortgagePct = this.mortgagePercentage || 0;
  const mortgageAmount = value * (mortgagePct / 100);
  const totalRequired = value + taxAmount;
  // Default due date: 30 days from now
  const defaultDueDate = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);

  // Remove existing unpaid auto-generated installments (preserve paid ones)
  this.installments = this.installments.filter(
    i => !i.autoGenerated || i.status === 'paid'
  );

  // Mortgage installment
  if (mortgageAmount > 0) {
    this.installments.push({
      description: `Mortgage (${mortgagePct}% of value)`,
      installmentType: 'investment',
      amount: Math.round(mortgageAmount * 100) / 100,
      percentage: mortgagePct,
      currency,
      dueDate: defaultDueDate,
      status: 'pending',
      autoGenerated: 'mortgage',
      notes: 'Auto-generated from mortgage settings'
    });
  }

  // Sum only investment-type installments (excluding final-payment)
  const investmentInstallmentsTotal = this.installments
    .filter(i => i.installmentType === 'investment' && i.autoGenerated !== 'final-payment')
    .reduce((sum, i) => sum + (i.amount || 0), 0);

  // Final payment = total required - investment installments
  const finalPaymentAmount = totalRequired - investmentInstallmentsTotal;

  if (finalPaymentAmount > 0) {
    this.installments.push({
      description: 'Final Payment (remaining balance)',
      installmentType: 'investment',
      amount: Math.round(finalPaymentAmount * 100) / 100,
      currency,
      dueDate: defaultDueDate,
      status: 'pending',
      autoGenerated: 'final-payment',
      includeTax: taxAmount > 0,
      taxPercentage: taxAmount > 0 ? taxRate : null,
      notes: 'Auto-generated: total required minus investment installments'
    });
  }
};

const RealEstateInvestment = mongoose.model('RealEstateInvestment', realEstateInvestmentSchema);

module.exports = RealEstateInvestment;
